using NUnit.Framework;
using Automation_Test;

namespace Automation_Test;

[TestFixture]

public class TestSumm
{
    int randomInt;
    int randomInt2;
    Calculator calculator;

    [OneTimeSetUp]
    public void SetupForClass()
    {
        calculator = new Calculator();
        randomInt = new Random().Next(-100, 499);
        randomInt2 = new Random().Next(-350, 780);
    }

    [Test, Description("Check summ when operand_1 and operand_2 is generated by Random")]
    [Category("Random")]
    public void TestSumm_random()
    {
        //Action
        var actualResult = calculator.Summ(randomInt, randomInt2);
        var expectedResult = randomInt + randomInt2;

        Console.WriteLine($"Number 1: {randomInt}, Number 2: {randomInt2}");

        ////Assert
        Assert.That(actualResult, Is.EqualTo(expectedResult), $"Summ {randomInt} + {randomInt2} = {actualResult}");
    }

    [TestCase(-2, -6, -8), Description("Test Case: sum 2 negative values")]
    [TestCase(-4, -10, -14)]
    [TestCase(-1, -19, -20)]
    public void TestSumm_way1_negativeNumbers(int operand1, int operand2, int result)
    {
        //Action
        var actualResult = calculator.Summ(operand1, operand2);

        ////Assert
        Assert.That(actualResult, Is.EqualTo(result), $"Summ {operand1} + {operand2} = {actualResult}");
    }

    [TestCase(1, 2, ExpectedResult = 3), Description("Test Case: sum 2 positive values")]
    [TestCase(35, 18, ExpectedResult = 53)]
    [TestCase(125, 460, ExpectedResult = 585)]
    public int TestSumm_way2_positiveNumbers(int operand1, int operand2)
    {
        //Action
        var actualResult = calculator.Summ(operand1, operand2);

        return actualResult;
    }

    [Test, Description("Test sum - when operand_1 is in values, operand_2 is in the range")]
    [Category("Mix")]
    public void TestSumm_way3_mix(
        [Values(9 ,38 ,179)] int operand1,
        [Range(-15, 29, 5)] int operand2)
    {
        //Action
        var actualResult = calculator.Summ(operand1, operand2);
        var expectedResult = operand1 + operand2;

        //Assert
        Assert.AreEqual(actualResult, expectedResult, $"Summ {operand1} + {operand2} = {actualResult}");
    }

    [TearDown]
    public void TearDown()
    {
        Console.WriteLine("Summ - After each test");
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        Console.WriteLine("Summ - In the end after all tests");
    }
}
