using NUnit.Framework;
using Automation_Test;

namespace Automation_Test;

[TestFixture]

public class TestsMinus
{
    int randomInt;
    int randomInt2;
    Calculator calculator;

    [OneTimeSetUp]
    public void SetupForClass()
    {
        calculator = new Calculator();
        randomInt = new Random().Next(10, 399);
        randomInt2 = new Random().Next(-99, 700);
    }

    [Test, Description("Check minus when operand_1 and operand_2 is generated by Random")]
    [Category("Random")]
    public void TestMinus_random()
    {
        //Action
        var actualResult = calculator.Minus(randomInt, randomInt2);
        var expectedResult = randomInt - randomInt2;

        Console.WriteLine($"Number 1: {randomInt}, Number 2: {randomInt2}");

        ////Assert
        Assert.That(actualResult, Is.EqualTo(expectedResult), $"Minus {randomInt} - {randomInt2} = {actualResult}");
    }

    [TestCase(-2, -6, 4), Description("Test Case: minus 2 negative values")]
    [TestCase(-40, -101, 61)]
    [TestCase(-19, -8, -11)]
    public void TestMinus_way1_negativeNumbers(int operand1, int operand2, int result)
    {
        //Action
        var actualResult = calculator.Minus(operand1, operand2);

        ////Assert
        Assert.That(actualResult, Is.EqualTo(result), $"Minus {operand1} - {operand2} = {actualResult}");
    }

    [TestCase(1, 2, ExpectedResult = -1), Description("Test Case: minus 2 positive values")]
    [TestCase(35, 18, ExpectedResult = 17)]
    [TestCase(125, 460, ExpectedResult = -335)]
    public int TestMinus_way2_positiveNumbers(int operand1, int operand2)
    {
        //Action
        var actualResult = calculator.Minus(operand1, operand2);

        return actualResult;
    }

    [Retry(2)]
    [Test, Description("Test minus - when operand_1 is in values, operand_2 is in the range")]
    [Category("Mix")]
    public void TestMinus_way3_mix(
        [Values(78, 1500, 179)] int operand1,
        [Range(-150, 120, 35)] int operand2)
    {
        //Action
        var actualResult = calculator.Minus(operand1, operand2);
        var expectedResult = operand1 - operand2;

        //Assert
        Assert.AreEqual(actualResult, expectedResult, $"Minus {operand1} - {operand2} = {actualResult}");
    }

    [TearDown]
    public void TearDown()
    {
        Console.WriteLine("Minus - After each test");
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        Console.WriteLine("Minus - In the end after all tests");
    }
}
